# Generated by Django 4.0.5 on 2022-06-22 06:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='글 제목')),
                ('thumbnail', models.FileField(upload_to='product/', verbose_name='썸네일')),
                ('description', models.TextField(max_length=1000, verbose_name='글 내용')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='노출 시작일')),
                ('end_date', models.DateField(default=datetime.date(2022, 6, 29), verbose_name='노출 종료일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
