# Generated by Django 4.0.5 on 2022-06-21 06:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), verbose_name='노출 종료일'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='노출 시작일'),
            preserve_default=False,
        ),
    ]
