# Generated by Django 4.0.5 on 2022-06-22 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_end_date_article_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 6, 29), verbose_name='노출 종료일'),
        ),
    ]
