# Generated by Django 4.0.5 on 2022-06-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hobby_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='join_data',
            new_name='join_date',
        ),
    ]
