# Generated by Django 4.0.5 on 2022-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_join_data_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
    ]
